module AutoCorrect
  DICTS             = {
    # Ruby
    "ruby"          => "Ruby",
    "mri"           => "MRI",
    "rails"         => "Rails",
    "gem"           => "Gem",
    "rubygems"      => "RubyGems",
    "rubyonrails"   => "Ruby on Rails",
    "ror"           => "Ruby on Rails",
    "rubyconf"      => "RubyConf",
    "railsconf"     => "RailsConf",
    "rubytuesday"   => "Ruby Tuesday",
    "jruby"         => "JRuby",
    "mruby"         => "mRuby",
    "rvm"           => "RVM",
    "rbenv"         => "rbenv",
    "yard"          => "YARD",
    "rdoc"          => "RDoc",
    "rspec"         => "RSpec",
    "minitest"      => "MiniTest",
    "coffeescript"  => "CoffeeScript",
    "scss"          => "SCSS",
    "sass"          => "Sass",
    "railscasts"    => "RailsCasts",
    "execjs"        => "ExecJS",
    "cocoapods"     => "CocoaPods",
    "capybara"      => "Capybara",
    "rack"          => "Rack",
    "sinatra"       => "Sinatra",
    "lotus"         => "Lotus",
    "grape"         => "Grape",
    "unicorn"       => "Unicorn",
    "thin"          => "Thin",
    "puma"          => "Puma",
    "passenger"     => "Passenger",
    "activerecord"  => "ActiveRecord",
    "active-record" => "ActiveRecord",
    "activemodal"   => "ActiveModel",
    "activesupport" => "ActiveSupport",
    "datamapper"    => "DataMapper",
    "devise"        => "Devise",
    "cancancan"     => "CanCanCan",
    "resque"        => "Resque",
    "sidekiq"       => "Sidekiq",
    "turbolinks"    => "Turbolinks",
    "sprockets"     => "Sprockets",
    "redcarpet"     => "Redcarpet",
    "sunspot"       => "Sunspot",
    "carrierwave"   => "CarrierWave",
    "paperclip"     => "PaperClip",
    "simpleform"    => "Simple Form",
    "kaminari"      => "Kaminari",
    "will_paginate" => "will_paginate",
    "minimagick"    => "MiniMagick",
    "rmagick"       => "RMagick",
    "nokogiri"      => "Nokogiri",
    "god"           => "God",
    "eventmachine"  => "EventMachine",
    "simplecov"     => "SimpleCov",
    "brakeman"      => "Brakeman",
    "activeadmin"   => "ActiveAdmin",
    "railsadmin"    => "RailsAdmin",
    "capistrano"    => "Capistrano",
    "mina"          => "Mina",
    "puppet"        => "Puppet",
    "vagrant"       => "Vagrant",
    "chef"          => "Chef",
    "rubymotion"    => "RubyMotion",
    "irb"           => "IRB",
    "pry"           => "Pry",
    
    # Python

    # Node.js
    "nodejs"        => "Node.js",
    "npm"           => "NPM",

    # Go
    
    # PHP
    "php"           => "PHP",
    "pear"          => "Pear",
    
    # Cocoa
    "reactivecocoa" => "ReactiveCocoa",
    
    # Java 

    # Programming
    "ssh"           => "SSH",
    "web"           => "Web",
    "api"           => "API",
    "css"           => "CSS",
    "html"          => "HTML",
    "json"          => "JSON",
    "jsonp"         => "JSONP",
    "xml"           => "xml",
    "yaml"          => "YAML",
    "yml"           => "YAML",
    "ini"           => "INI",
    "csv"           => "CSV",
    "soap"          => "SOAP",
    "ajax"          => "Ajax",
    "messagepack"   => "MessagePack",
    "javascript"    => "JavaScript",
    "js"            => "JS",
    "png"           => "PNG",
    "dsl"           => "DSL",
    "tdd"           => "TDD",
    "bdd"           => "BDD",
    "cgi"           => "CGI",
    "asp.net"       => "ASP.NET",
    ".net"          => ".NET",
    "rest"          => "REST",
    "orm"           => "ORM",
    "oauth"         => "OAuth",
    "oauth2"        => "OAuth2",
    "i18n"          => "I18N",
    "markdown"      => "Markdown",


    # Sites
    "github"        => "GitHub",
    "gist"          => "Gist",
    "ruby_china"    => "Ruby China",
    "ruby-china"    => "Ruby China",
    "rubychina"     => "Ruby China",
    "v2ex"          => "V2EX",
    "heroku"        => "Heroku",
    "stackoverflow" => "Stack Overflow",
    "stackexchange" => "StackExchange",
    

    # Databases
    "mysql"         => "MySQL",
    "postgresql"    => "PostgreSQL",
    "sqlite"        => "SQLite",
    "mongodb"       => "MongoDB",
    "rethinkdb"     => "RethinkDB",
    "elasticsearch" => "Elasticsearch",
    "sphinx"        => "Sphinx",
    
    # System
    "window"        => "Windows",
    "linux"         => "Linux",
    "mac"           => "Mac",
    "osx"           => "OS X",
    "ubuntu"        => "Ubuntu",
    "rhel"          => "RHEL",
    "centos"        => "CentOS",
    "archlinux"     => "Arch Linux",
    "redhat"        => "RedHat",

    # OpenSource Projects
    "gitlab"        => "GitLab",
    "gitlabci"      => "GitLab CI",
    "fontawsome"    => "FontAwsome",
    "bootstrap"     => "Bootstrap",
    "less"          => "Less",
    "jquery"        => "jQuery",
    "requirejs"     => "RequireJS",
    "underscore"    => "Underscore",
    "backbone"      => "Backbone",
    "seajs"         => "SeaJS",
    "imagemagick"   => "ImageMagick",
    "fluentd"       => "Fluentd",
    "ffmpeg"        => "FFMPEG",
    
    # Tools
    "git"           => "Git",
    "svn"           => "SVN",
    "vim"           => "VIM",
    "emacs"         => "Emacs",
    "textmate"      => "TextMate",
    "sublime"       => "Sublime",
    "rubymine"      => "RubyMine",
    "sequelpro"     => "Sequel Pro",
    "virtualbox"    => "VirtualBox",
    "safari"        => "Safari",
    "chrome"        => "Chrome",
    "ie"            => "IE",
    "dash"          => "Dash",
    "termal"        => "Termal",
    "iterm"         => "iTerm",
    "iterm2"        => "iTerm2",
    "iwork"         => "iWork",
    "iphoto"        => "iPhoto",
    "ibook"         => "iBook",
    "tweetbot"      => "TweetBot",
    "sparrow"       => "Sparrow",
    "photoshop"     => "Photoshop",
    "office"        => "Office",

    # Misc
    "ios"           => "iOS",
    "iphone"        => "iPhone",
    "android"       => "Android",
    "osx"           => "OS X",
    "mac"           => "Mac",
    "imac"          => "iMac",
    "macbookpro"    => "MacBook Pro",
    "macbook"       => "MacBook",
    "rmbp"          => "rMBP",
    "wi-fi"         => "Wi-Fi",
    "wifi"          => "Wi-Fi",
    "vps"           => "VPS",
    "vpn"           => "VPN",
    "arm"           => "ARM",
    "cpu"           => "CPU",
    
  }
end
