name: Release
on:
  push:
    branches:
      - "feat/rust-ext"
    tags:
      - "v*"

jobs:
  release_gem:
    name: Release RubyGems
    strategy:
      fail-fast: false
      matrix:
        include:
          - cargo_build_target: x86_64-unknown-linux-gnu
            target: x86_64-linux
            os: ubuntu-latest
          - cargo_build_target: x86_64-apple-darwin
            target: x86_64-darwin
            os: macos-latest
          - cargo_build_target: aarch64-apple-darwin
            target: arm64-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y libclang-dev
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.cargo_build_target }}
      - name: Cross Ruby
        run: |
          gem install rake-compiler
          mkdir ~/.rake-compiler/
          rake-compiler cross-ruby HOST=${{ matrix.target }} VERSION=3.1.0
      - name: Compile
        env:
          CARGO_BUILD_TARGET: ${{ matrix.cargo_build_target }}
        run: |
          bundle
          rake compile
          rake package
          mv pkg/*.gem pkg/auto-correct-${{ matrix.target }}.gem
          # gem push -k ${{ secrets.RUBYGEMS_API_KEY }} pkg/auto-correct-${{ matrix.target }}.gem
      - uses: actions/upload-artifact@v2
        with:
          name: auto-correct-${{ matrix.target }}
          path: pkg/auto-correct-${{ matrix.target }}.gem
          retention-days: 1
